spring:
  application:
    name: pazs
  cloud:
    nacos:
      config:
        server-addr: 192.168.31.131:8848
        file-extension: yaml
      discovery:
        server-addr: 192.168.31.131:8848

server:
  port: 8071